spring.application.name=module
server.port=8088

# PostgreSQL 설정
spring.datasource.url=jdbc:postgresql://localhost:5432/community_board
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# HikariCP 설정
spring.datasource.hikari.read-only=false

supabase.url=https://hkyvuusfwiyjiekjtkwq.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhreXZ1dXNmd2l5amlla2p0a3dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDU2NzgsImV4cCI6MjA2MDE4MTY3OH0.PiAIKBaqMPcMwpaK4H6qoubbztooLSIFec2B2VmsF8o

# SpringDoc OpenAPI
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.showExtensions=true
springdoc.swagger-ui.showCommonExtensions=true